
#' Get EXIF data for images files
#' 
#' Checks for command length, such that windows command length policies are respected.
#'
#' @param filename A vector of filenames (like that generated by \code{list.files(..., full.names=TRUE)})
#' @param quiet \code{FALSE} if status updates are desired, \code{TRUE} otherwise.
#' 
#' @return a data.frame of photo EXIF information
#' 
#' @examples
#' files <- list.files(path.package("rfuncs"), recursive=TRUE, pattern="*.png", full.names=TRUE)
#' exifinfo <- getexif(files)
#' 
#' @export
#'
getexif <- function(filename, quiet=FALSE) {
  if(length(filename) == 0) {
    return(data.frame())
  }
  
  foreach <- foreach::foreach
  `%do%` <- foreach::`%do%`
  
  if(.Platform$OS.type == "windows") {
    exiftoolpath <- file.path(path.package("rfuncs"), "exiftool/exiftool-win")
    commandlength <- 8191 #according to https://support.microsoft.com/en-us/kb/830473
  } else {
    exiftoolpath <- file.path(path.package("rfuncs"), "exiftool/exiftool")
    #according to the interweb this should be around 100kb, but 50kb should do
    #(is 'getconf ARG_MAX' on mac, equals 262144)
    commandlength <- 50*1024
  }
  
  if(!quiet) message("Generating command line arguments...")
  
  filenameslist <- list(filename)
  nominallen <- length(filename)
  commands <- foreach(fnames=filenameslist, .combine=c) %do% {.exifcommand(exiftoolpath, fnames)}
  while(any(nchar(commands) >= commandlength) && commandlength != 0 && nominallen >= 2) {
    #subdivide files until all commands are less than commandlength
    nominallen <- as.integer(nominallen / 2)
    if((length(filename) %% nominallen) == 0) {
      ngroups = length(filename) / nominallen
    } else {
      ngroups <- as.integer(length(filename)/nominallen) + 1
    }
    filenameslist <- foreach(i=1:ngroups) %do% {
      minind <- ((i-1)*nominallen+1)
      maxind <- min(i*nominallen, length(filename))
      filename[minind:maxind]
    }
    commands <- foreach(fnames=filenameslist, .combine=c) %do% {.exifcommand(exiftoolpath, fnames)}
  }

  if(!quiet) message("Running ", length(commands), " commands")
  return(foreach(command=commands, .combine=plyr::rbind.fill, .multicombine=TRUE) %do% {
    if(!quiet) message(command)
    read.csv(textConnection(system(command, intern=TRUE)), stringsAsFactors = FALSE)
  })
}

#helper function to generate exif commands
.exifcommand <- function(exiftoolpath, fnames) {
  paste(shQuote(exiftoolpath), "-n -csv", paste(shQuote(fnames), collapse=" "))
}